// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Hp8VhZkl4nOQ5aAvBnrz0oRMkrOW84s',
    appId: '1:142273036261:web:02a961d4aebb51833a790c',
    messagingSenderId: '142273036261',
    projectId: 'portfolio-e187f',
    authDomain: 'portfolio-e187f.firebaseapp.com',
    storageBucket: 'portfolio-e187f.appspot.com',
    measurementId: 'G-26H4C80FQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHOKEXXXs2Clw1CmkVapPrtIhjN2-5fsc',
    appId: '1:142273036261:android:6bfdb9104f34022f3a790c',
    messagingSenderId: '142273036261',
    projectId: 'portfolio-e187f',
    storageBucket: 'portfolio-e187f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZghq6qZ4_y8dKDjkphUE8--kHX_sLyCo',
    appId: '1:142273036261:ios:fd508d5472c521f33a790c',
    messagingSenderId: '142273036261',
    projectId: 'portfolio-e187f',
    storageBucket: 'portfolio-e187f.appspot.com',
    iosClientId: '142273036261-mn92uqb8n8mthf52hsb1shtsilu9ebb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );
}
